
spring:
  datasource:
    password: root
    url: jdbc:mysql://127.0.0.1:3307/hospital  # ???
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    show-sql: true

