
spring:
  datasource:
    password: admin
    url: jdbc:mysql://127.0.0.1:3307/hospital  # ???
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format-sql: true
    show-sql: true
server:
  port: 8081

#  main:
#    web-application-type: none